name: Lighthouse

on:
  push:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: purcell/setup-emacs@master
        with:
          version: 24.5
      - run: npm install
      - run: ./build.el
      - run: npx lhci autorun
